# Standalone Docker Compose for D&D Site
# Use this if you want to run the D&D site completely separate from nexus365

version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    container_name: dnd_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dnd_net

networks:
  dnd_net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
