backend:
  name: github
  repo: skamprogiannis/dnd-site
  branch: main

media_folder: "content/Characters/Lucian/images"
public_folder: "Characters/Lucian/images"

collections:
  - name: "characters"
    label: "Characters"
    folder: "content/Characters"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "npcs"
    label: "NPCs"
    folder: "content/NPCs"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Race", name: "race", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
