backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  repo: skamprogiannis/dnd-site

media_folder: "content/lucian/images" # Media files will be stored in the repo under content/images
public_folder: "lucian/images" # The src attribute for uploaded media

collections:
  - name: "characters" # Used in routes, e.g., /admin/collections/blog
    label: "Characters" # Used in the UI
    folder: "content/lucian" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
